### ISSUE TITLE
Set-KeyVaultSecret adds quotation around secret value in key vault

### ISSUE THREAD

**Issue by lupusbytes** [atc-net/atc-snippets#57]
The triple quotes that was added in https://github.com/atc-net/atc-snippets/commit/fd5bd26cedf9f89db3a474962da1fe9cf78549d4, #53 consistently adds double quotes around the secret value I'm storing.
Example value `foo` gets set in the keyvault as `"foo"`

PowerShell 7.3.3 on Linux.

**Comment by cjakobsen** [comment]
The old code without the quotes could not store certain secret values, we need to figure out another way of doing this.

**Comment by lupusbytes** [comment]
Could be that Windows and Linux, and perhaps even PowerShell 5 and 7 have different behaviour when it comes to escaping. I have seen that before.
Best that we find a solution that works on both Windows and Linux, because both are used in pipelines. 
Lets test this together and find a working solution for all operating systems and runtimes.
